// Generated by scripts/optimize-showcase-images.mjs. Do not edit manually.

export const showcaseImages = {
  "racecarRender": {
    "src": "/showcase/optimized/racecar-render-1300.1fe0ec889e3c.webp",
    "srcSet": "/showcase/optimized/racecar-render-650.15d64021f16f.webp 650w, /showcase/optimized/racecar-render-1300.1fe0ec889e3c.webp 1300w, /showcase/optimized/racecar-render-2240.2af24e8092c3.webp 2240w",
    "width": 2688,
    "height": 1568,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAAwBSJZwAAgWoCnQLAAD1PnjWeYRJqnX7UwnnNsyPZ6F4052EO0+2ZMVqy/6Vi7nBWSbvYLSqGlCAAA==",
    "variants": [
      {
        "src": "/showcase/optimized/racecar-render-650.15d64021f16f.webp",
        "width": 650,
        "bytes": 27336
      },
      {
        "src": "/showcase/optimized/racecar-render-1300.1fe0ec889e3c.webp",
        "width": 1300,
        "bytes": 89052
      },
      {
        "src": "/showcase/optimized/racecar-render-2240.2af24e8092c3.webp",
        "width": 2240,
        "bytes": 182240
      }
    ]
  },
  "racecarOrigin": {
    "src": "/showcase/optimized/racecar-origin-1300.d121690611af.webp",
    "srcSet": "/showcase/optimized/racecar-origin-168.2d76c8a6bd5c.webp 168w, /showcase/optimized/racecar-origin-650.6f2e79383030.webp 650w, /showcase/optimized/racecar-origin-1300.d121690611af.webp 1300w, /showcase/optimized/racecar-origin-2240.ac5cf7bc74bf.webp 2240w",
    "width": 5945,
    "height": 3505,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAkAAwBSJYwCw7EO9OgM+sAA/vee82eFe1JQzSXEUjGxjr2qpOYBVtZ7DMFdbW2367ok36P8f8FmZRZTQAAA",
    "variants": [
      {
        "src": "/showcase/optimized/racecar-origin-168.2d76c8a6bd5c.webp",
        "width": 168,
        "bytes": 2834
      },
      {
        "src": "/showcase/optimized/racecar-origin-650.6f2e79383030.webp",
        "width": 650,
        "bytes": 24824
      },
      {
        "src": "/showcase/optimized/racecar-origin-1300.d121690611af.webp",
        "width": 1300,
        "bytes": 82718
      },
      {
        "src": "/showcase/optimized/racecar-origin-2240.ac5cf7bc74bf.webp",
        "width": 2240,
        "bytes": 203402
      }
    ]
  }
} as const;
